### ISSUE TITLE
Affiliate DB from Google Sheets -> Airtable

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/.public#2]

**Comment by mehediok1** [comment]
Almost finished but there are some issues I marked it problems. Other active affiliate links were transferred to Airtable.

**Comment by devinschumacher** [comment]
- [ ] problems - https://docs.google.com/spreadsheets/d/18ylbfm9du9dIW9JmYpSwb5NLWu2Jf2pt-R-IEpCdFG0/edit?pli=1#gid=1241555474
