### ISSUE TITLE
issuu

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/.public#44]
ISSUU:  Can you add the URL, Username, email, password, etc. to the airtable for the ISSUU profiles we already have (from seo wrappers?)

[Slack Message](https://serp.slack.com/archives/D04HRMKJY74/p1706791017882359?thread_ts=1706791017.882359&cid=D04HRMKJY74)

**Comment by mehediok1** [comment]
I have added 65 issue accounts on airtable.

https://airtable.com/appg1IKYY8prqKCxe/tblIySh99svb24o1O/viwwSjcgqI3AAJIiR?blocks=hide
